---
- hosts: webservers
  tasks:
    - name: Installeerime php uuema
      apt: name=php update_cache=yes state=latest

    - name: Installeerime libapache-mod-php uuema
      apt: name=libapache2-mod-php update_cache=yes state=latest

    - name: Installeerime php-mysql uuema
      apt: name=php-mysql update_cache=yes state=latest

    - name: Installime python3-pymysql ansible jaoks
      apt: name=python3-pymysql update_cache=yes state=latest

    - name: Loome phpinfo.php faili
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /var/www/html/phpinfo.php