
---
- hosts: web
  tasks:
    - name: PHPMyAdmin webserver 'Apache2'
      debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='apache2' vtype='multiselect'

    - name: PHPMyAdmin database install
      debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

    - name: PHPMyAdmin app password 'qwerty'
      debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='qwerty' vtype='password'

    - name: PHPMyAdmin admin password 'qwerty'
      debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='qwerty' vtype='password'

    - name: PHPMyAdmin app password 'qwerty'
      debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='qwerty' vtype='password'

    - name: Installime phpmyadmin
      apt: name=phpmyadmin update_cache=yes state=latest

    - name: Restartime apache2 teenuse
      service:
        name: apache2
        state: restarted
